### PR TITLE
Scalaz

### PR DESCRIPTION
**Pull request by NeQuissimus**
- The OSGI package exports were wrong
- Add `ip4s-scalaz` module
- Update README to point to new modules
- Split guide and fix it

### CODE REVIEW

**Comment by NeQuissimus** [comment]
@mpilquist Would you be able to cut a release with this? :)

**Comment by mpilquist** [comment]
Awesome, I'll release 1.1 after this gets merged. Thanks for the guide updates too!

Any thoughts on how best to handle scalaz 7.3 and scalaz 8 interop modules down the road?

**Comment by mpilquist** [comment]
1.1.0 has been published

**Comment by NeQuissimus** [comment]
@mpilquist 7.3 should "just work" with the 7.2 code. I would simply drop 7.2 and replace it with a 7.3 dependency.
And 8... I am not too worried about yet, that will still be a little while. Maybe publish `ip4s-scalaz8` for milestones, then drop 7.3 support when 8.0 is out.

And thank you for the quick turnaround!

**Pull request merged**
