### PR TITLE
Adds cats interop for SourceSpecificMulticast.

### PR DESCRIPTION
**Pull request by matthughes**

### CODE REVIEW

**Comment by mpilquist** [comment]
Do we need the same for AnySourceMulticast?

**Comment by matthughes** [comment]
No AnySourceMulticast works because the typeclasses cover any subclass of MulticastJoin.  I rewrote the Multicast typeclasses to use the same pattern of capturing the wrapping type.

**Comment by mpilquist** [comment]
Build failed due to binary compatibility breakages.

**Comment by matthughes** [comment]
Fixed

**Pull request merged**
