### PR TITLE
publish ScalaCheck Arbitraries as a separate test-kit artifact

### PR DESCRIPTION
**Pull request by bpholt**
I was wondering if you'd consider publishing the ScalaCheck `Arbitrary` instances as a separate module. I'm writing another library that uses `IpAddress` as part of its data model and want to generate arbitrary instances, including arbitrary IP addresses, and it seems like the best way to do that is to reuse the arbitraries from this library.

I had to move the tests from `core` to `testKit` to work around a dependency loop (`testKit/compile` depends on `core/compile` for the main types it's testing, but `core/test` would have depended on `testKit/compile` for the `Arbitrary` instances, and sbt complained about that setup). Another (possibly clearer) alternative would be to move the tests themselves to a separate `tests` project that relies on both `core` and `testKit`—let me know if you'd prefer that approach.

(The Scala 2.11 and 2.12 builds look like they're passing, and 2.13-M5 is failing. 2.13-M5 is also failing on master due to missing previous-version artifacts for the MiMa step. I disabled MiMa for the new artifact to avoid it failing 2.11 and 2.12 builds, so it should be enabled later, should this PR be released.)

### CODE REVIEW

**Comment by bpholt** [comment]
FWIW, this seems to me like a pretty mechanical contribution, which may not require the CLA to be signed. I'm going to run the CLA by our legal department for review, but that may take some time to complete, so if we can merge without signing, that's fine with me.

**Comment by mpilquist** [comment]
:+1: Changes look good to me. Note we're using ScalaCheck 1.14 here, which doesn't work with the current stable version of ScalaTest -- we really need ScalaTest 3.1.0 to be guaranteed longer term compatibility. I'm good with merging this as-is though b/c ScalaTest isn't a compile time dependency of the test kit project.

Re: CLA, we do require it so I can't merge until then. Thanks!

**Comment by bpholt** [comment]
Sounds good… now just waiting on our legal department. 🙂

**Comment by bpholt** [comment]
@mpilquist I signed the CLA this afternoon!

**Comment by bpholt** [comment]
@mpilquist Friendly bump on this PR… any chance this could be merged and released soon? Thanks!

**Comment by mpilquist** [comment]
Sorry! Totally missed this one. Will get a release out tonight.

**Comment by mpilquist** [comment]
1.2.0 was published to Sonatype this morning.

**Pull request merged**
